// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmweobzsrlxwypxuoycr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtd2VvYnpzcmx4d3lweHVveWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTA3MDIsImV4cCI6MjA3MzEyNjcwMn0.WHUqHOJ1OwlHqKOyFGaZMPfhQScdB6pAonn6n1Lm0yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});